language: node_js
sudo: false

node_js:
  - "10"

cache:
  yarn: true

branches:
  only:
    - master

script:
  - yarn coverage

before_install:
  - yarn global add codecov

after_success:
  - codecov
